"""empty message

Revision ID: 161b820b4666
Revises: b468c0f6ca49
Create Date: 2023-01-14 11:04:15.971294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161b820b4666'
down_revision = 'b468c0f6ca49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('hair_color', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    # ### end Alembic commands ###
