"""empty message

Revision ID: 6f4b247cabf0
Revises: e54a749f4c34
Create Date: 2023-01-16 07:39:19.504395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f4b247cabf0'
down_revision = 'e54a749f4c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorite_people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('favorite_people_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favorite_people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_favorite_people')
    # ### end Alembic commands ###
