"""empty message

Revision ID: e54a749f4c34
Revises: 336dbd3491e7
Create Date: 2023-01-14 17:40:52.402823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e54a749f4c34'
down_revision = '336dbd3491e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorite_planets', schema=None) as batch_op:
        batch_op.drop_constraint('user_favorite_planets_favorite_planet_id_key', type_='unique')
        batch_op.drop_constraint('user_favorite_planets_user_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorite_planets', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_favorite_planets_user_id_key', ['user_id'])
        batch_op.create_unique_constraint('user_favorite_planets_favorite_planet_id_key', ['favorite_planet_id'])

    # ### end Alembic commands ###
